version: '3.8'

services:
  flutter_app:
    build:
      context: ./flutter_app
    container_name: flutter_app
    ports:
      - "8080:80"
    volumes:
      - ./flutter_app/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx  # For log scraping

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  loki:
    image: grafana/loki:latest
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    ports:
      - "${TEMPO_PORT}:4317"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - tempo_data:/tmp/tempo
      - ./tempo.yaml:/etc/tempo.yaml

  prometheus:
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "${ALLOY_PORT}:12345"
      - "8889:8889" # metrics
    volumes:
      - ./alloy-config/config.alloy:/etc/alloy/config.alloy
      - /var/log/nginx:/var/log/nginx
    command: ["run", "/etc/alloy/config.alloy"]

volumes:
  grafana_data:
  tempo_data:
